name: CI

on:
  pull_request:
  push:
    branches:
      - main

# cancel in-progress job when a new push is performed
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: System dependencies (Ubuntu)
      run: |
        sudo apt-get install texlive-full latexmk python3-pip fonts-firacode
        pip install alectryon

    - name: Download Libertinus Fonts
      uses: robinraju/release-downloader@v1
      with:
        repository: alerque/libertinus
        tag: v7.051
        fileName:  Libertinus-7.051.tar.zst

    - name: Unzip and install Libertinus Font
      run: |
        tar --use-compress-program=unzstd -xvf Libertinus-7.051.tar.zst
        sudo cp -r Libertinus-7.051/static/OTF /usr/local/share/fonts
        fc-cache -f -v

    - name: Build
      run: |
        cd Manuscript
        latexmk -xelatex -shell-escape main.tex
