name: CI

on:
  pull_request:
  push:
    tags:
      - '**'
    branches:
      - main

# cancel in-progress job when a new push is performed
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        package-file: thesis-deps.txt

    - name: System dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install fonts-firacode fonts-liberation fonts-lmodern -y
        pip install pygments latexminted

    - name: Download Libertinus Fonts
      uses: robinraju/release-downloader@v1
      with:
        repository: alerque/libertinus
        tag: v7.051
        fileName: Libertinus-7.051.tar.zst

    - name: Unzip and install Libertinus Font
      run: |
        tar --use-compress-program=unzstd -xvf Libertinus-7.051.tar.zst
        sudo cp -r Libertinus-7.051/static/OTF /usr/local/share/fonts
        fc-cache -f -v

    - name: Build
      run: |
        cd Manuscript
        latexmk -xelatex -shell-escape main.tex -output-directory=_build -quiet || (cat _build/main.log; exit 1)

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Manuscript/_build/main.pdf
