name: CI

on:
  pull_request:
  push:
    tags:
      - '**'
    branches:
      - main

# cancel in-progress job when a new push is performed
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [5.2.0]

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        package-file: thesis-deps.txt

    - name: System dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install fonts-firacode fonts-liberation fonts-lmodern opam -y
        pip install pygments latexminted

    - name: Download Libertinus Fonts
      uses: robinraju/release-downloader@v1
      with:
        repository: alerque/libertinus
        tag: v7.051
        fileName: Libertinus-7.051.tar.zst

    - name: Unzip and install Libertinus Font
      run: |
        tar --use-compress-program=unzstd -xvf Libertinus-7.051.tar.zst
        sudo cp -r Libertinus-7.051/static/OTF /usr/local/share/fonts
        fc-cache -f -v

    - name: Restore OPAM cache
      id: cache-opam-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.opam
        key: ${{ matrix.version }}
  
    - name: Setup OPAM
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      run: |
        opam init --yes --disable-sandboxing --no-setup --shell=sh --compiler=${{ matrix.version }}
        eval $(opam env --switch=${{ matrix.version }})
        opam pin --yes ott https://github.com/dc-mak/ott.git#dont-marshal-exn

    - name: Save OPAM cache
      uses: actions/cache/save@v4
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      with:
        path: ~/.opam
        key: ${{ matrix.version }}

    - name: Build
      run: |
        cd src
        mkdir -p _build/mevens
        mv main.tex old_minted.tex && tail -n +2 old_minted.tex > main.tex # hack to build with newer version of minted
        eval $(opam env --switch=${{ matrix.version }})
        make || (cat _build/*.log; exit 1)
        texcount -inc main.tex | tee _build/wordcount.tex

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          src/_build/main.pdf
          src/_build/wordcount.tex
          src/_build/defns.pdf
          src/_build/soudness.pdf
