name: CI

on:
  pull_request:
  push:
    tags:
      - '**'
    branches:
      - main

# cancel in-progress job when a new push is performed
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        package-file: thesis-deps.txt

    - name: System dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install latexmk biber python3-pip fonts-firacode
        pip install alectryon -v
        find ~/.local -name 'alectryon' -type d

    - name: Download Libertinus Fonts
      uses: robinraju/release-downloader@v1
      with:
        repository: alerque/libertinus
        tag: v7.051
        fileName: Libertinus-7.051.tar.zst

    - name: Unzip and install Libertinus Font
      run: |
        tar --use-compress-program=unzstd -xvf Libertinus-7.051.tar.zst
        sudo cp -r Libertinus-7.051/static/OTF /usr/local/share/fonts
        fc-cache -f -v

    - name: Build
      run: |
        cd Manuscript
        echo '{ "custom_lexers": { "pygments_lexer.py": "eb1e113289fea184bab8e3f6ca7246e7ad5b283604fecd9e2d43e4426f8f31b0" } }' >> ~/.latexminted_config
        latexmk -xelatex -shell-escape main.tex

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Manuscript/main.pdf
